version: "3.8"
services:
  postgres-db:
    container_name: todo
    image: postgres # use latest official postgres version
    restart: always
    environment:
      POSTGRES_USER: acc_dev
      POSTGRES_PASSWORD: acc_dev12
      POSTGRES_DB: todo
      POSTGRES_HOST_AUTH_METHOD: password
    ports:
      - "5436:5432"

volumes:
  postgresql_data:
    driver: local